default_platform(:android)

platform :android do
  desc "Build signed APK and AAB for prod"
  lane :prod_release do

    gradle(
      task: "clean"
    )

    gradle(
      task: "assembleProdRelease",
      print_command: true
    )

    gradle(
      task: "bundleProdRelease",
      print_command: true
    )

  end
end
